### ISSUE TITLE
build_all.sh issue -> arduino_generic_quad_spi_controller2 18.1 not found

### ISSUE THREAD

**Issue by ghost** [vidor-libraries/VidorBitstream#6]
Hey, 
I think I've done everything from the instruction and now I have issues, first one is the file from title missing. Can you help me?
`2020.03.13.08:31:17 Error: MKRVIDOR4000_EXO_lite_sys.qspi: Component <b>arduino_generic_quad_spi_controller2 18.1</b> not found or could not be instantiated
Error: MKRVIDOR4000_EXO_lite_sys.qspi.avl_mem: Data width must be of power of two and between 8 and 4096`

**Comment by pnndra** [comment]
i think you either didn't run apply_quartus_patches.sh or that failed to apply. can you please doublecheck? patches may fail to apply if you're using a different version of quartus .

**Comment by ghost** [comment]
thanks for the answer, you're right - I'm using 18.1 on windows when patches are for 18.0 and there are problems with dos2unix conversion because of 0x013 symbols... Do you know, how could I fix them, or downgrade to 18.0 is the only option?

**Comment by pnndra** [comment]
Sorry for the slow reply. I guess by now you downgraded, which for now is the best option.
