### ISSUE TITLE
Warning: nina_uart: Component type arduino_16550_uart is not in the library

### ISSUE THREAD

**Issue by Nglungtat** [vidor-libraries/VidorBitstream#8]
Hi,
I run apply_quartus_patches.sh in Nios II Command Shell(intelFPGA_lite 18.1)
The result is as following print screen jpegs, (I don't know how to record the information when .sh running)
![create_arduino_16550_uart_01](https://user-images.githubusercontent.com/69842086/90625849-c3e24800-e24c-11ea-89ad-d5e886a5d7ad.jpg)
![create_arduino_16550_uart_02](https://user-images.githubusercontent.com/69842086/90625850-c47ade80-e24c-11ea-8ea5-cbc6fe5d8451.jpg)
![create_arduino_16550_uart_03](https://user-images.githubusercontent.com/69842086/90625851-c5137500-e24c-11ea-8e50-e76ed59d1d1c.jpg)
![create_arduino_16550_uart_04](https://user-images.githubusercontent.com/69842086/90625855-c5ac0b80-e24c-11ea-9833-6536232f0724.jpg)
![create_arduino_16550_uart_05](https://user-images.githubusercontent.com/69842086/90625842-c2188480-e24c-11ea-9415-4bf43d92d988.jpg)
![create_arduino_16550_uart_06](https://user-images.githubusercontent.com/69842086/90625848-c3e24800-e24c-11ea-8fa1-887c3a74be9e.jpg)
I think create "arduino_16550_uart" component is not success, because in file "mkrvidor4000_graphics_lite_sys_generation" shows:
Progress: Adding nina_uart [arduino_16550_uart 18.1]
Warning: nina_uart: Component type arduino_16550_uart is not in the library
Who can help me to solve it, thanks

**Comment by Nglungtat** [comment]
I reinstall intelFPGA_lite 18.0, try to run "apply_quartus_patches", the result same to 18.1.
![create_arduino_16550_uart-18_0](https://user-images.githubusercontent.com/69842086/90851949-c8bc0e80-e3a8-11ea-8457-faf36a258ded.jpg)
![create_arduino_16550_uart_2-18_0](https://user-images.githubusercontent.com/69842086/90852204-73ccc800-e3a9-11ea-946b-8232b5f46ea9.jpg)

In 18.0/ip/altera/arduino_16550_uart/, It shown:
[arduino_16550_uart_hw_tcl_rej.txt](https://github.com/vidor-libraries/VidorBitstream/files/5106818/arduino_16550_uart_hw_tcl_rej.txt)

**Comment by JuliDi** [comment]
Hey,
I had the same problem and what fixed it was adding the following block to `altera_components.ipx` in `<quartus_path>/18.1/ip/altera`:
```
  <component
   name="arduino_16550_uart"
   file="arduino_16550_uart/arduino_16550_uart_hw.tcl"
   displayName="ARDUINO 16550 Compatible UART Intel FPGA IP"
   version="18.1"
   description="UART with run-time configurability and 16550 compatible register space"
   tags="AUTHORSHIP=Intel Corporation /// CONNECTION_TYPES=avalon,clock,conduit,interrupt,reset"
   categories="Interface Protocols/Serial"
   factory="TclModuleFactory">
  <tag2 key="ALLOW_GREYBOX_GENERATION" value="true" />
  <tag2 key="ANALYZE_HDL" value="false" />
  <tag2 key="COMPONENT_EDITABLE" value="true" />
  <tag2 key="COMPONENT_HIDE_FROM_QUARTUS" value="true" />
  <tag2 key="COMPONENT_HIDE_FROM_SOPC" value="true" />
  <tag2 key="ELABORATION_CALLBACK" value="elaboration" />
  <tag2 key="INSTANTIATE_IN_SYSTEM_MODULE" value="true" />
  <tag2 key="SUPPORTED_FILE_SETS" value="QUARTUS_SYNTH,SIM_VERILOG,SIM_VHDL" />
  <tag2 key="TCL_PACKAGE_VERSION" value="12.0" />
  <tag2 key="VALIDATION_CALLBACK" value="validation" />
  <documentUrl displayName="DATASHEET" type="DATASHEET" url="http://www.altera.com" />
  <documentUrl
     displayName="User Guide"
     type="OTHER"
     url="https://documentation.altera.com/#/link/sfo1400787952932/iga1404147076304" />
  <documentUrl
     displayName="Release Notes"
     type="OTHER"
     url="https://documentation.altera.com/#/link/hco1416836145555/hco1416836653221" />
 </component>
```

This is a copy of the `altera_16550_uart` component and I replaced `altera_16550_uart` with `arduino_16550_uart` to match the arduino uart file name.

Hope this helps.

**Comment by pnndra** [comment]
please note also that 16550 UART requires a full license. for this reason we added lite templates that exclude the use of such IP
