### ISSUE TITLE
What is the relationship with vidor-libraries/VidorFPGA?

### ISSUE THREAD

**Issue by gmacario** [vidor-libraries/VidorBitstream#9]
It looks like the contents of this repository and  https://github.com/vidor-libraries/VidorFPGA
are quite similar.

Could you please clarify which one is supposed to be used and for which purpose?

See also https://github.com/vidor-libraries/VidorFPGA/issues/3

Thanks!

**Comment by pnndra** [comment]
this repository is more recent and contains more templates and all the tools required to create arduino libraries that include FPGA bitstream
